// Try/Catch error handling
try {
alert("Hello User 9_events");
console.log("ok");
}
catch(err) {
document.getElementById("msgBox").innerHTML = err.message; }
finally {
// If needed, you can do something here regardless of what happens in try/catch
}



